export const MOCK = [
  { id:  1, folio: "RPT-2025-041", cliente: "AUDI MEXICO SA DE CV",                 tipo: "Dimensional",   magnitud: "Longitud",     tecnico: "Ing. Sánchez", fechaRecepcion: "2025-06-26", fechaEmision: "2025-06-28", equipos: 8,  status: "emitido" },
  { id:  2, folio: "RPT-2025-040", cliente: "FOXCONN INDUSTRIAL INTERNET SA DE CV",  tipo: "Eléctrica",     magnitud: "Voltaje/Corriente", tecnico: "Ing. Pérez",   fechaRecepcion: "2025-06-25", fechaEmision: "2025-06-27", equipos: 5,  status: "revision" },
  { id:  3, folio: "RPT-2025-039", cliente: "ASSA ABLOY MEXICO SA DE CV",            tipo: "Presión",       magnitud: "Presión",      tecnico: "Ing. Sánchez", fechaRecepcion: "2025-06-24", fechaEmision: null,         equipos: 3,  status: "proceso" },
  { id:  4, folio: "RPT-2025-038", cliente: "HONEYWELL AEROSPACE TECHNOLOGIES",      tipo: "Temperatura",   magnitud: "Temperatura",  tecnico: "Ing. Ruiz",    fechaRecepcion: "2025-06-22", fechaEmision: "2025-06-25", equipos: 12, status: "entregado" },
  { id:  5, folio: "RPT-2025-037", cliente: "BOMBARDIER AEROSPACE CHIHUAHUA",        tipo: "Dimensional",   magnitud: "Longitud",     tecnico: "Ing. Pérez",   fechaRecepcion: "2025-06-20", fechaEmision: "2025-06-24", equipos: 6,  status: "emitido" },
  { id:  6, folio: "RPT-2025-036", cliente: "DELPHI TECHNOLOGIES MFG",               tipo: "Eléctrica",     magnitud: "Resistencia",  tecnico: "Ing. Sánchez", fechaRecepcion: "2025-06-18", fechaEmision: "2025-06-22", equipos: 4,  status: "entregado" },
  { id:  7, folio: "RPT-2025-035", cliente: "CONTINENTAL AUTOMOTIVE MFG",            tipo: "Dimensional",   magnitud: "Longitud",     tecnico: "Ing. Ruiz",    fechaRecepcion: "2025-06-15", fechaEmision: "2025-06-20", equipos: 15, status: "entregado" },
  { id:  8, folio: "RPT-2025-034", cliente: "GRUPO BIMBO SAB DE CV",                 tipo: "Masa",          magnitud: "Masa",         tecnico: "Ing. Pérez",   fechaRecepcion: "2025-06-14", fechaEmision: "2025-06-18", equipos: 7,  status: "entregado" },
  { id:  9, folio: "RPT-2025-033", cliente: "BAXTER SA DE CV",                       tipo: "Temperatura",   magnitud: "Temperatura",  tecnico: "Ing. Sánchez", fechaRecepcion: "2025-06-12", fechaEmision: "2025-06-16", equipos: 9,  status: "entregado" },
  { id: 10, folio: "RPT-2025-032", cliente: "LEXMARK INTERNATIONAL SA DE CV",        tipo: "Eléctrica",     magnitud: "Voltaje/Corriente", tecnico: "Ing. Ruiz", fechaRecepcion: "2025-06-10", fechaEmision: "2025-06-14", equipos: 3,  status: "entregado" },
  { id: 11, folio: "RPT-2025-031", cliente: "AUDI MEXICO SA DE CV",                  tipo: "Fuerza",        magnitud: "Fuerza",       tecnico: "Ing. Pérez",   fechaRecepcion: "2025-06-08", fechaEmision: "2025-06-12", equipos: 2,  status: "entregado" },
  { id: 12, folio: "RPT-2025-030", cliente: "INTERNATIONAL PACKAGING CORP",          tipo: "Presión",       magnitud: "Presión",      tecnico: "Ing. Sánchez", fechaRecepcion: "2025-06-05", fechaEmision: "2025-06-10", equipos: 5,  status: "entregado" },
];
